CREATE TABLE `tbcursos` (
    `idCurso` int(10) UNSIGNED NOT NULL,
    `nomeCurso` VARCHAR(255) NOT NULL,
    `datainicial` date NOT NULL DEFAULT '0000-00-00',
    `horainicial` TIME,
    `datafinal` date NOT NULL DEFAULT '0000-00-00',
    `horafinal`TIME,
    `vagas` INT(10) NOT NULL,
    `cargaHoraria` INT(10),
    `freqMinima` INT(10),
    `categorias` varchar(255) NOT NULL,
    `valor` int(10) NOT NULL,
    `valorSocio` int(10) NOT NULL,
    `valorParceiro` int(10) NOT NULL,
    `valorNaoQuite` int(10) NOT NULL,
    `tipoVencimento` varchar(10) NOT NULL,
    `vencimento` date DEFAULT '0000-00-00',
    `ndias` int(10),
    `status`int (1) NOT NULL
)